/**
 * Canonical 36-entry portfolio types.
 * Mirror of content/catalogue/portfolio-36.json — generated by
 * scripts/build-portfolio-manifest.mjs from owner source documents.
 */

export type PortfolioEntryType = 'SUITE' | 'WORKFLOW';

export type PortfolioStatus =
  | 'PUBLIC_DEMO'
  | 'WORKFLOW_KIT'
  | 'PUBLIC_CATALOGUE_SUPERVISED'
  | 'INTERNAL_CONTROLLED_PILOT'
  | 'ENTERPRISE_INTEGRATION'
  | 'CONDITIONAL_VALIDATION';

export type ValidationStatus = 'PASS' | 'CONDITIONAL' | 'NOT_RUN';

export interface PortfolioPricing {
  kitFromUsd: number | null;
  sprintFromUsd: number | null;
  pilotFromUsd: number | null;
  workspaceFromUsd: number | null;
  note: string | null;
}

export interface PortfolioValidation {
  runDate: string;
  testFocus: string | null;
  result: string | null;
  measuredEvidence: string | null;
  sources: string[];
  limitations: string[];
}

/** Legacy demo wiring carried over for the 15 workflows. */
export interface PortfolioDemo {
  available: boolean;
  fixturePath: string | null;
  fixtureSource: string | null;
  fixtureLabel: string | null;
  prompt: string;
  inputSchema: Record<string, unknown>;
  outputSchema: Record<string, unknown>;
  legacyPricing: Record<string, unknown> | null;
  legacyLimitations: string[];
}

export interface PortfolioEntry {
  id: string;
  slug: string;
  type: PortfolioEntryType;
  title: string;
  parentId: string | null;
  parentRoute?: string;
  route: string;
  legacySlug: string | null;
  category: string;
  buyer: string | null;
  humanApprover: string | null;
  humanApprovalRequired: boolean;
  status: PortfolioStatus;
  staticDesignScore: number | null;
  validationStatus: ValidationStatus;
  publicDemo: boolean;
  experiencePattern: string;
  jobToBeDone: string | null;
  definition: string | null;
  modules: string[];
  useCases: string[];
  exclusions: string[];
  inputSummary: string[];
  outputSummary: string[];
  validators: string[];
  controlRequirements: string[];
  failureModes: string[];
  runbook: string[];
  productBoundary: string | null;
  buyerValue: string | null;
  publicValidation: PortfolioValidation;
  autonomousActions: never[];
  validationReport: string | null;
  promptReference: string | null;
  pricing: PortfolioPricing;
  demo: PortfolioDemo | null;
  updatedAt: string;
}

export interface PortfolioManifest {
  manifest: {
    name: string;
    version: string;
    generatedAt: string;
    purpose: string;
    counts: { total: number; suites: number; workflows: number };
    statusLegend: Record<PortfolioStatus, string>;
    sourceDocuments: string[];
    integrityNote: string;
  };
  entries: PortfolioEntry[];
}
