// services/fullkonk.github.ts

import { GeneratedFile } from '../types';

export interface GitHubConfig {
  token:  string;
  owner:  string;
  repo:   string;
  branch: string;
  message: string;
}

export interface GitHubExportResult {
  success:  boolean;
  prUrl?:   string;
  commitSha?: string;
  filesUploaded: number;
  errors:   string[];
}

// Base64 encode for GitHub API (works in both Node.js and Browser)
function toBase64(str: string): string {
  if (typeof Buffer !== 'undefined') {
    return Buffer.from(str, 'utf-8').toString('base64');
  }
  return btoa(unescape(encodeURIComponent(str)));
}

// Get or create branch
async function ensureBranch(config: GitHubConfig): Promise<string> {
  const base = `https://api.github.com/repos/${config.owner}/${config.repo}`;
  const headers = {
    'Authorization': `Bearer ${config.token}`,
    'Content-Type':  'application/json',
    'Accept':        'application/vnd.github+json',
  };

  // Get repo default branch
  const repoRes = await fetch(base, { headers });
  if (!repoRes.ok) throw new Error('Cannot access repository. Check token, owner, and repo name.');
  const repoData = await repoRes.json();
  const defaultBranch = repoData.default_branch || 'main';

  // Get default branch SHA
  const refRes = await fetch(`${base}/git/refs/heads/${defaultBranch}`, { headers });
  if (!refRes.ok) throw new Error(`Cannot access default branch '${defaultBranch}'.`);
  const refData = await refRes.json();
  const sha = refData.object.sha;

  // Check if branch exists
  const branchRes = await fetch(`${base}/git/refs/heads/${config.branch}`, { headers });
  if (branchRes.status === 404) {
    // Create branch
    await fetch(`${base}/git/refs`, {
      method:  'POST',
      headers,
      body: JSON.stringify({ ref: `refs/heads/${config.branch}`, sha }),
    });
  }

  return defaultBranch;
}

// Get existing file SHA (needed for updates)
async function getFileSha(
  config: GitHubConfig,
  path: string,
): Promise<string | undefined> {
  const res = await fetch(
    `https://api.github.com/repos/${config.owner}/${config.repo}/contents/${path}?ref=${config.branch}`,
    {
      headers: {
        'Authorization': `Bearer ${config.token}`,
        'Accept':        'application/vnd.github+json',
      },
    },
  );
  if (!res.ok) return undefined;
  const data = await res.json();
  return data.sha;
}

// Upload a single file
async function uploadFile(
  config: GitHubConfig,
  file: GeneratedFile,
): Promise<void> {
  const sha = await getFileSha(config, file.path);

  const body: Record<string, string> = {
    message: config.message,
    content: toBase64(file.content),
    branch:  config.branch,
  };
  if (sha) body.sha = sha;

  const res = await fetch(
    `https://api.github.com/repos/${config.owner}/${config.repo}/contents/${file.path}`,
    {
      method:  'PUT',
      headers: {
        'Authorization': `Bearer ${config.token}`,
        'Content-Type':  'application/json',
        'Accept':        'application/vnd.github+json',
      },
      body: JSON.stringify(body),
    },
  );

  if (!res.ok) {
    const err = await res.json();
    throw new Error(err.message ?? `Failed to upload ${file.path}`);
  }
}

// Create PR
async function createPR(config: GitHubConfig, baseBranch = 'main'): Promise<string> {
  const res = await fetch(
    `https://api.github.com/repos/${config.owner}/${config.repo}/pulls`,
    {
      method:  'POST',
      headers: {
        'Authorization': `Bearer ${config.token}`,
        'Content-Type':  'application/json',
        'Accept':        'application/vnd.github+json',
      },
      body: JSON.stringify({
        title: `[fullKONK_>] ${config.message}`,
        head:  config.branch,
        base:  baseBranch,
        body:  `Generated by fullKONK_> on konkred.xyz\n\n${config.message}`,
      }),
    },
  );
  if (!res.ok) return '';
  const data = await res.json();
  return data.html_url ?? '';
}

// Main export function
export async function exportToGitHub(
  files: GeneratedFile[],
  config: GitHubConfig,
): Promise<GitHubExportResult> {
  const errors: string[] = [];
  let filesUploaded = 0;
  let prUrl = '';
  let defaultBranch = 'main';

  try {
    defaultBranch = await ensureBranch(config);
  } catch (err: any) {
    return { success: false, errors: [err.message], filesUploaded: 0 };
  }

  for (const file of files) {
    try {
      await uploadFile(config, file);
      filesUploaded++;
    } catch (err: any) {
      errors.push(`${file.path}: ${err.message}`);
    }
  }

  if (filesUploaded > 0 && config.branch !== defaultBranch) {
    try {
      prUrl = await createPR(config, defaultBranch);
    } catch {
      // PR creation failure is non-fatal
    }
  }

  return {
    success:       filesUploaded > 0,
    prUrl:         prUrl || undefined,
    filesUploaded,
    errors,
  };
}
